// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.sping.domain;

import co.sping.domain.Inform;

privileged aspect Inform_Roo_JavaBean {
    
    public String Inform.getName() {
        return this.name;
    }
    
    public void Inform.setName(String name) {
        this.name = name;
    }
    
}
