// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.sping.domain;

import co.sping.domain.ITT;
import java.util.Date;

privileged aspect ITT_Roo_JavaBean {
    
    public Date ITT.getDayly() {
        return this.dayly;
    }
    
    public void ITT.setDayly(Date dayly) {
        this.dayly = dayly;
    }
    
}
