// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.sping.domain;

import co.sping.domain.Newnew;
import java.lang.Folat;

privileged aspect Newnew_Roo_JavaBean {
    
    public Folat Newnew.getNum() {
        return this.num;
    }
    
    public void Newnew.setNum(Folat num) {
        this.num = num;
    }
    
}
